#!/bin/bash
# from Higemaru on https://unix.stackexchange.com/questions/60778/how-can-i-get-an-alert-when-my-battery-is-about-to-die-in-linux-mint
# used with (after chmod +x)
## $ crontab -e
## */5 * * * * /home/julgoe/myConfigFiles/checkLowBattery

# set -euo pipefail

POWERSUPPLY="/sys/class/power_supply/AC/online" # could be different on your system!
TOO_LOW=10 # how low is too low?
NOT_CHARGING="0"
ICON="/usr/share/icons/Adwaita/scalable/legacy/battery-caution-charging-symbolic.svg" # eye candy

# get the correct dbus
tmpStr=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/"$(pidof i3)"/environ)
export DBUS_SESSION_BUS_ADDRESS=${tmpStr:25:200}
export LC_NUMERIC=en_US.UTF-8

# BATTERY_LEVEL=$(acpi -b | grep -P -o '[0-9]+(?=%)')
BATTERY_LEVEL=$(acpi -b | grep  -oP "[0-9]+(?=%)")
COMPARING_FLOATS=$(echo "$BATTERY_LEVEL<$TOO_LOW" | bc -l)
STATUS=$(cat $POWERSUPPLY)

if [ "$COMPARING_FLOATS" -eq 1 -a "$STATUS" == "$NOT_CHARGING" ]
then
	# if dunst is asleep, activate
	if [ "$(dunstctl is-paused)" = 'true' ]; then
		/home/julgoe/myConfigFiles/i3scripts/dunstToggle.sh resume
	fi
	dunstify -u critical -i "$ICON" -r 4444 -t 60000 "Battery low" "Battery level is $(printf %.0f "$BATTERY_LEVEL")%!"
fi

exit 0
