#!/bin/bash
# easy way to diff slurm outputs without the timestamps, escape codes

set -euo pipefail


[ "$#" -lt 2 ] && echo "needs more than 2 arguments" && exit
# neovim doesn't have `vimdiff` but `nvim -d`
if type nvim >/dev/null 2>&1; then
	vimdiff="nvim -d "
else
	vimdiff=vimdiff
fi

modifiedFiles=""
for f in "$@"; do
	! [ -f "$f" ] && echo "$f not a file" && continue
	modifiedFiles="$modifiedFiles <(cat $f | sed 's/\x1b\[[0-9;]*m//g' | sed -r 's/[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{1,3}//g')"
done

eval "$vimdiff $modifiedFiles"
