#!/bin/zsh

# get qr code for wifi

# might not work yet
if [[ "$#" -lt 1 ]]; then
	echo "needs an SSID as an argument"
	return
fi

# needs qrencode and nmcli
if type nmcli >/dev/null 2>&1 && type qrencode >/dev/null 2>&1; then
	echo "creates qr code for connection '$1'"
else
	echo "Needs qrencode and nmcli"
	return 1
fi

#### actual stuff

local ssid psk
ssid=$(nmcli -s -g connection.id con show "$1")
psk=$(nmcli -s -g 802-11-wireless-security.psk con show "$1")
if [ -z "$ssid" -o -z "$psk" ]; then
	echo "Problem with ssid or psk, investigate"
	echo "|ssid||psk|"
	echo "|${ssid}||${psk}|"
	return 1
fi
# echo "${ssid}||$psk"

# create string for qrencode
str="WIFI:S:${ssid};T:WPA2;P:${psk};;"
echo "ssid is '${ssid}' and pw '${psk}'"
# encode it
qrencode -t png -s 10 -o /tmp/wifi.png "$str"
# view it
xprop -id "$WINDOWID" -f _NET_WM_WINDOW_TYPE 8u -set _NET_WM_WINDOW_TYPE splash
display /tmp/wifi.png
rm /tmp/wifi.png

return 0
