#!/bin/bash

# set -euo pipefail

LocOfScript=$(dirname "$(readlink -f "$0")")

everythingOK=true

# check whether install script runs through
tmpString=$("$LocOfScript/install.sh")
if [[ $? -ne 0 ]]; then
	echo "##### There is a problem with the install script, the versions in the repo and on your computer are not identical"
	echo -e "$tmpString"
	echo "(If you think everything is correct, commit with '--no-verify')"
	everythingOK=false
fi

# check current crontabList
tmpString=$(diff "$LocOfScript/crontabList" <(crontab -l))
if [[ $? -ne 0 ]]; then
	echo "The saved list of cronjobs differ like this:"
	echo "$tmpString"
	echo "(If you think everything is correct, commit with '--no-verify')"
	everythingOK=false
	crontab -l > "$LocOfScript/crontabList"
fi

# check whether new packages have been installed
# install them via https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Install_packages_from_a_list
# To filter out from the list the foreign packages, the previous command line can be enriched as follows:
# pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort pkglist.txt))
tmpString=$(diff "$LocOfScript/listOfPackages.txt" <(pacman -Qqe))
if [[ $? -ne 0 ]]; then
	echo "The saved list of installed packages and the current installed packages differ like this:"
	echo "$tmpString"
	echo "(If you think everything is correct, commit with '--no-verify')"
	everythingOK=false
	pacman -Qqe > "$LocOfScript/listOfPackages.txt"
fi

# check whether new pips have been installed
tmpString=$(diff "$LocOfScript/listOfPipPackages.txt" <(pip list))
if [[ $? -ne 0 ]]; then
	echo "The saved list of installed pip packages and the current installed pip packages differ like this:"
	echo "$tmpString"
	echo "(If you think everything is correct, commit with '--no-verify')"
	everythingOK=false
	pip list > "$LocOfScript/listOfPipPackages.txt"
fi

if ! $everythingOK; then
	exit 1
fi
