#!/bin/sh

# logging is found e.g. with `journalctl --follow | grep sleep`

# this will lock the computer if it has been sleeping for longer than 30M
logger "$0 $1 $2 $3 $4 lock file"
case "$1" in
	pre)
		date +%s > /home/julgoe/.tmp_lidclosingaction_tmstmp &
		;;
	post)
		tmp=$(cat /home/julgoe/.tmp_lidclosingaction_tmstmp)
		echo "open" > /home/julgoe/.tmp_lidclosingaction_tmstmp
		if [ ! $tmp = "open" ]; then
			if [ "$(($(date +%s)-$tmp))" -ge "$((30*60))" ]; then
				USER=$(ps -C i3 -o user=)
				if test $USER; then
					# only lock if not locked yet
					if ! pgrep i3lock >/dev/null; then
						# DISPLAY=:0.0 su $USER -c /home/julgoe/myConfigFiles/toolbox/lock.sh
						DISPLAY=:0.0 su $USER -c /home/julgoe/myConfigFiles/toolbox/lockAlt.sh
						#"xautolock -locknow"
						# if it isn't working check whether theres a xautolock running and try to lokc with -locknow in terminal
					fi
				fi
			fi
		fi
		;;
esac


